### PR TITLE
Fixed errors with variable lookup.

### LINKED ISSUE #11: Nested hook execution in package "shazam"
I got the following log:
```
[1/4] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/shazam-DistToNearest-Vignette.R
Loading required package: ggplot2
Error in ÈØ{U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: distToNearest ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning messages:
1: In HÌ{U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
2: In  :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
3: In Ø5V{U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
4: In ÈØ{U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_promise_created
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/shazam-DistToNearest-Vignette.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ---- eval=TRUE, warning=FALSE, message=FALSE----------------------------
    # Subset example data to one sample
    library(shazam)
    data(ExampleDb, package="alakazam")
    db <- subset(ExampleDb, SAMPLE == "-1h")
    
    ## ---- eval=TRUE, warning=FALSE-------------------------------------------
    # Use nucleotide Hamming distance and normalize by junction length
    dist_ham <- distToNearest(db, model="ham", first=FALSE, normalize="len", 
                              nproc=1)
    
    # Use genotyped V assignments, a 5-mer model and no normalization
    dist_s5f <- distToNearest(db, vCallColumn="V_CALL_GENOTYPED", model="hh_s5f", 
                              first=FALSE, normalize="none", nproc=1)
    
    ## ---- eval=TRUE, warning=FALSE, fig.width=7------------------------------
    # Generate Hamming distance histogram
    library(ggplot2)
    p1 <- ggplot(subset(dist_ham, !is.na(DIST_NEAREST)),
                 aes(x=DIST_NEAREST)) + 
        theme_bw() + 
        xlab("Hamming distance") + 
        ylab("Count") +
        scale_x_continuous(breaks=seq(0, 1, 0.1)) +
        geom_histogram(color="white", binwidth=0.02) +
        geom_vline(xintercept=0.12, color="firebrick", linetype=2)
    plot(p1)
    
    ## ---- eval=TRUE, warning=FALSE, fig.width=7------------------------------
    # Generate HH_S5F distance histogram
    p2 <- ggplot(subset(dist_s5f, !is.na(DIST_NEAREST)),
                 aes(x=DIST_NEAREST)) + 
        theme_bw() + 
        xlab("HH_S5F distance") + 
        ylab("Count") +                                                                                                                                                                                                                                                       
        scale_x_continuous(breaks=seq(0, 50, 5)) +                                                                                                                                                                                                                            
        geom_histogram(color="white", binwidth=1) +                                                                                                                                                                                                                           
        geom_vline(xintercept=7, color="firebrick", linetype=2)                                                                                                                                                                                                               
    plot(p2)                                                                                                                                                                                                                                                                  
    
    ## ---- eval=TRUE, warning=FALSE, fig.width=7------------------------------
    # Find threshold using gmm method
    output <- findThreshold(dist_ham$DIST_NEAREST, method="gmm", model="gamma-gamma")
    
    # Plot distance histogram, Gaussian fits, and optimum threshold
    plot(output, binwidth=0.02, title="GMM Method: gamma-gamma")
    
    # Print threshold
    print(output)
    
    ## ---- eval=TRUE, warning=FALSE, fig.width=7------------------------------
    # Find threshold using density method
    output <- findThreshold(dist_ham$DIST_NEAREST, method="density")
    threshold <- output@threshold
    
    # Plot distance histogram, density estimate and optimum threshold
    plot(output, title="Density Method")
    
    # Print threshold
    print(output)
    
    ## ----fields, eval=TRUE, warning=FALSE------------------------------------
    dist_fields <- distToNearest(ExampleDb, model="ham", first=FALSE, 
                                 normalize="len", fields="SAMPLE", 
                                 nproc=1)
    
    ## ---- eval=TRUE, warning=FALSE, fig.width=7------------------------------
    # Generate grouped histograms
    p4 <- ggplot(subset(dist_fields, !is.na(DIST_NEAREST)), 
                 aes(x=DIST_NEAREST)) + 
        theme_bw() + 
        xlab("Grouped Hamming distance") + 
        ylab("Count") +
        geom_histogram(color="white", binwidth=0.02) +
        geom_vline(xintercept=0.12, color="firebrick", linetype=2) +
        facet_grid(SAMPLE ~ ., scales="free_y")
    plot(p4)
    
    ## ----cross, eval=TRUE, warning=FALSE-------------------------------------
    dist_cross <- distToNearest(ExampleDb, model="ham", first=FALSE, 
                                normalize="len", cross="SAMPLE", nproc=1)
    
    ## ---- eval=TRUE, warning=FALSE, fig.width=7------------------------------
    # Generate cross sample histograms
    p5 <- ggplot(subset(dist_cross, !is.na(CROSS_DIST_NEAREST)), 
                 aes(x=CROSS_DIST_NEAREST)) + 
        theme_bw() + 
        xlab("Cross-sample Hamming distance") + 
        ylab("Count") +
        geom_histogram(color="white", binwidth=0.02) +
        geom_vline(xintercept=0.12, color="firebrick", linetype=2) +
        facet_grid(SAMPLE ~ ., scales="free_y")
    plot(p5)
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/shazam-DistToNearest-Vignette.OK')
```

### LINKED ISSUE #12: Nested hook execution in package "tidytext"
I got the following log:
```
[1/4] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/tidytext-tidying_casting.R
Loading required package: NLP

Attaching package: âNLPâ

The following object is masked from âpackage:ggplot2â:

    annotate

Error in ÈúìrU : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: %>% ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning messages:
1: In à2WsU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
2: In š2WsU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
3: In ÈúìrU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
4: In ÈúìrU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_promise_created
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/tidytext-tidying_casting.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----echo = FALSE--------------------------------------------------------
    knitr::opts_chunk$set(fig.width = 7, fig.height = 7, message = FALSE, warning = FALSE)
    library(ggplot2)
    theme_set(theme_bw())
    
    ## ------------------------------------------------------------------------
    library(tm)
    data("AssociatedPress", package = "topicmodels")
    AssociatedPress
    
    ## ------------------------------------------------------------------------
    library(dplyr)
    library(tidytext)
    
    ap_td <- tidy(AssociatedPress)
    
    ## ------------------------------------------------------------------------
    ap_sentiments <- ap_td %>%
      inner_join(get_sentiments("bing"), by = c(term = "word"))
    
    ap_sentiments
    
    ## ------------------------------------------------------------------------
    library(tidyr)
    
    ap_sentiments %>%
      count(document, sentiment, wt = count) %>%
      ungroup() %>%
      spread(sentiment, n, fill = 0) %>%
      mutate(sentiment = positive - negative) %>%
      arrange(sentiment)
    
    ## ----fig.width = 7, fig.height = 5---------------------------------------
    library(ggplot2)
    
    ap_sentiments %>%
      count(sentiment, term, wt = count) %>%
      ungroup() %>%
      filter(n >= 150) %>%
      mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
      mutate(term = reorder(term, n)) %>%
      ggplot(aes(term, n, fill = sentiment)) +
      geom_bar(stat = "identity") +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
      ylab("Contribution to sentiment")
    
    ## ------------------------------------------------------------------------
    library(methods)
    
    data("data_corpus_inaugural", package = "quanteda")
    d <- quanteda::dfm(data_corpus_inaugural, verbose = FALSE)
    
    d
    
    tidy(d)
    
    ## ------------------------------------------------------------------------
    ap_td
    
    # cast into a Document-Term Matrix
    ap_td %>%
      cast_dtm(document, term, count)
    
    # cast into a Term-Document Matrix
    ap_td %>%
      cast_tdm(term, document, count)
    
    # cast into quanteda's dfm
    ap_td %>%
      cast_dfm(term, document, count)
    
    
    # cast into a Matrix object
    m <- ap_td %>%
      cast_sparse(document, term, count)
    class(m)
    dim(m)
    
    ## ------------------------------------------------------------------------
    reut21578 <- system.file("texts", "crude", package = "tm")
    reuters <- VCorpus(DirSource(reut21578),
                       readerControl = list(reader = readReut21578XMLasPlain))
    
    reuters
    
    ## ------------------------------------------------------------------------
    reuters_td <- tidy(reuters)
    reuters_td
    
    ## ------------------------------------------------------------------------
    library(quanteda)
    
    data("data_corpus_inaugural")
    
    data_corpus_inaugural
    
    inaug_td <- tidy(data_corpus_inaugural)
    inaug_td
    
    ## ------------------------------------------------------------------------
    inaug_words <- inaug_td %>%
      unnest_tokens(word, text) %>%
      anti_join(stop_words)
    
    inaug_words
    
    ## ------------------------------------------------------------------------
    inaug_freq <- inaug_words %>%
      count(Year, word) %>%
      ungroup() %>%
      complete(Year, word, fill = list(n = 0)) %>%
      group_by(Year) %>%
      mutate(year_total = sum(n),
             percent = n / year_total) %>%
      ungroup()
    
    inaug_freq
    
    ## ------------------------------------------------------------------------
    models <- inaug_freq %>%
      group_by(word) %>%
      filter(sum(n) > 50) %>%
      do(tidy(glm(cbind(n, year_total - n) ~ Year, .,
                  family = "binomial"))) %>%
      ungroup() %>%
      filter(term == "Year")
    
    models
    
    models %>%
      filter(term == "Year") %>%
      arrange(desc(abs(estimate)))
    
    ## ------------------------------------------------------------------------
    library(ggplot2)
    
    models %>%
      mutate(adjusted.p.value = p.adjust(p.value)) %>%
      ggplot(aes(estimate, adjusted.p.value)) +
      geom_point() +
      scale_y_log10() +
      geom_text(aes(label = word), vjust = 1, hjust = 1,
                check_overlap = TRUE) +
      xlab("Estimated change over time") +
      ylab("Adjusted p-value")
    
    ## ------------------------------------------------------------------------
    library(scales)
    
    models %>%
      top_n(6, abs(estimate)) %>%
      inner_join(inaug_freq) %>%
      ggplot(aes(Year, percent)) +
      geom_point() +
      geom_smooth() +
      facet_wrap(~ word) +
      scale_y_continuous(labels = percent_format()) +
      ylab("Frequency of word in speech")
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/tidytext-tidying_casting.OK')

```

### LINKED ISSUE #13: Nested hook execution in package "queuecomputer"
I got the following log:
```
[1/1] Done vignettes for package: queuecomputer
[1/2] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/queuecomputer-MMk_queues.R
Error in ËV : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: summary ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning messages:
1: In éÄV :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
2: In ÈX6ÃV :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/queuecomputer-MMk_queues.sqlite',verbose=FALSE)                                                                                                                                                                                                                                                                                                                                                                                      
dyntrace(dyntracer, {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    library(queuecomputer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    P_0_func <- function(rho, k){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      sum_i <- rep(NA, k)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      for(i in 0:I(k-1))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        sum_i[i+1] <- rho^i / factorial(i)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      p_0 <- 1/(sum(sum_i) + rho^k/(factorial(k - 1) * (k - rho)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      return(p_0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    P_n <- function(rho,n,k){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      p_0 <- P_0_func(rho, k)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      if(n <= k){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        output <- rho^n / factorial(n) * p_0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      } else {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        output <- rho^n / (factorial(k) * k^(n-k)) * p_0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
      return(output)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    Lq <- function(rho, k){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
      p_0 <- P_0_func(rho, k)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      output <- p_0 * rho^{k+1} / ( factorial(k-1) * (k - rho)^2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      return(output)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    set.seed(1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    n_customers <- 1e6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    lambda_a <- 1/1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    lambda_s <- 1/0.8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    interarrivals <- rexp(n_customers, lambda_a)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    arrivals <- cumsum(interarrivals)
    
    service <- rexp(n_customers, lambda_s)
    
    rho <- (1/lambda_s) / (1/lambda_a)
    
    ## ------------------------------------------------------------------------
    
    k = 1
    
    p_0 <- P_n(rho, n=0, k)
    
    ### System lengths -----------------------
    Vectorize(P_n, "n")(rho=rho, n=c(0:30), k = k)
    
    ### Estimated queue length -----------------
    LQ <- Lq(rho, k)
    LQ
    
    ### Estimated units in system -----------
    LQ + rho
    
    Ws = 1/lambda_s
    Wq = LQ / lambda_a
    W = Ws + Wq
    
    Wq # Mean waiting time (time in queue)
    W # Mean response time (time in system)
    
    
    ## ------------------------------------------------------------------------
    
    MM1 <- queue_step(arrivals = arrivals, service = service, servers = k)
    
    MM1_summary <- summary(MM1)
    
    MM1_summary$slength_sum
    
    # Mean queue length
    MM1_summary$qlength_mean
    
    # Mean system length (number of customers in system)
    MM1_summary$slength_mean
    
    MM1_summary$mwt # Mean waiting time
    MM1_summary$mrt # Mean response time
    
    ## ------------------------------------------------------------------------
    
    k = 3
    
    p_0 <- P_n(rho, 0, k)
    
    ### System lengths -----------------------
    Vectorize(P_n, "n")(rho=rho, n=c(0:30), k = k)
    
    ### Estimated queue length -----------------
    LQ <- Lq(rho, k)
    LQ
    
    ### Estimated units in system -----------
    LQ + rho
    
    Ws = 1/lambda_s
    Wq = LQ / lambda_a
    W = Ws + Wq
    
    Wq # Mean waiting time (time in queue)
    W # Mean response time (time in system)
    
    
    ## ------------------------------------------------------------------------
    
    
    MM3 <- queue_step(arrivals = arrivals, service = service, servers = k)
    
    MM3_summary <- summary(MM3)
    
    MM3_summary$slength_sum
    
    # Mean queue length
    MM3_summary$qlength_mean
    
    # Mean system length (number of customers in system)
    MM3_summary$slength_mean
    
    MM3_summary$mwt # Mean waiting time
    MM3_summary$mrt # Mean response time
    
    
    ## ------------------------------------------------------------------------
    
    # Setup ----------
    
    
    set.seed(2)
    
    n_customers <- 1e6
    
    lambda_a <- 1/1
    lambda_s <- 1/2.5
    
    interarrivals <- rexp(n_customers, lambda_a)
    
    arrivals <- cumsum(interarrivals)
    
    service <- rexp(n_customers, lambda_s)
    
    rho <- (1/lambda_s) / (1/lambda_a)
    
    
    ## ------------------------------------------------------------------------
    
    rho <- (1/lambda_s) / (1/lambda_a)
    
    # MM3 queue ------------------------------
    
    k = 3
    
    ## Theoretical -------------------
    
    p_0 <- P_n(rho, 0, k)
    
    ### System lengths -----------------------
    Vectorize(P_n, "n")(rho=rho, n=c(0:30), k = k)
    
    ### Estimated queue length -----------------
    LQ <- Lq(rho, k)
    LQ
    
    ### Estimated units in system -----------
    LQ + rho
    
    ### Waiting times -----------
    Ws = 1/lambda_s
    Wq = LQ / lambda_a
    W = Ws + Wq
    
    Wq # Mean waiting time (time in queue)
    W # Mean response time (time in system)
    
    
    ## ------------------------------------------------------------------------
    
    
    MM3_2 <- queue_step(arrivals = arrivals, service = service, servers = k)
    
    MM3_2_summary <- summary(MM3_2)
    
    MM3_2_summary$slength_sum
    
    # Mean queue length
    MM3_2_summary$qlength_mean
    
    # Mean system length (number of customers in system)
    MM3_2_summary$slength_mean
    
    MM3_2_summary$mwt # Mean waiting time
    MM3_2_summary$mrt # Mean response time
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/queuecomputer-MMk_queues.OK')

```

### LINKED ISSUE #14: Nested hook execution in package "nonmemica"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/nonmemica-parameter-table.R

Attaching package: ânonmemicaâ

The following object is masked from âpackage:stringrâ:

    fixed

Error in ÈØ®QŽU : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: partab ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In (ÏàYŽU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted

```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/nonmemica-parameter-table.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----eval=FALSE----------------------------------------------------------
    #  install.packages(repos=NULL,'../nonmemica_0.1.zip') # supply your path and version
    #  library(nonmemica)
    
    ## ----echo=FALSE, results='hide'------------------------------------------
    library(nonmemica)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  partab(1001, project='../model')
    
    ## ----eval=FALSE----------------------------------------------------------
    #  options(project = '../model')
    #  partab(1001)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  methods(format)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  partab(1001)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  1001 %>% partab
    
    ## ----eval=FALSE----------------------------------------------------------
    #  2 %>% sqrt %>% signif(3)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  signif(sqrt(2),digits=3)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  partab(1001, xmlfile='..model/1001.xml')
    
    ## ----eval=FALSE----------------------------------------------------------
    #  partab(1001, bootcsv='..model/1001/bootstrap_results.csv')
    
    ## ----eval=FALSE----------------------------------------------------------
    #  partab(1001, ctlfile = '../models/1001.ctl',fields = c('symbol','label','unit')).
    
    ## ------------------------------------------------------------------------
    library(magrittr)
    library(nonmemica)
    options(project = system.file('project/model',package='nonmemica'))
    1001 %>% definitions %>% head
    
    ## ----eval = FALSE--------------------------------------------------------
    #  1001 %>% definitions(write=T)
    #  1001 %>% partab(ctlfile = NULL)
    
    ## ------------------------------------------------------------------------
    partab(1001)
    
    ## ------------------------------------------------------------------------
    x <- partab(1001)
    
    ## ----eval=FALSE----------------------------------------------------------
    #  partab(1001, verbose=TRUE)
    
    ## ------------------------------------------------------------------------
    1001 %>% partab(
      format = F, 
      ci = F, 
      relative = F, 
      digits = NULL
    )
    
    ## ------------------------------------------------------------------------
    library(knitr)
    1001 %>% partab %>% kable
    
    ## ------------------------------------------------------------------------
    library(pander)
    1001 %>% partab %>% pander(justify='right')
    
    ## ------------------------------------------------------------------------
    library(ReporteRs)
    1001 %>% partab %>% as.docx %>% as.file('1001.docx')
    x <- as.flextable(partab(1001))
    x
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/nonmemica-parameter-table.OK')

```

### LINKED ISSUE #15: Segfault in package "polypoly"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/polypoly-overview.R
# A tibble: 180 x 3
   Reaction  Days Subject
      <dbl> <dbl>  <fctr>
 1 249.5600     0     308
 2 258.7047     1     308
 3 250.8006     2     308
 4 321.4398     3     308
 5 356.8519     4     308
 6 414.6901     5     308
 7 382.2038     6     308
 8 290.1486     7     308
 9 430.5853     8     308
10 466.3535     9     308
# ... with 170 more rows
Loading required package: Matrix

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: 
 2: 
 3: 
 4: 
 5: 
 6: 
 7: 
 8: 
 9: 
An irrecoverable exception occurred. R is aborting now ...
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/polypoly-overview.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ---- include = FALSE----------------------------------------------------
    knitr::opts_chunk$set(
      comment = "#>",
      collapse = TRUE)
    
    ## ------------------------------------------------------------------------
    # orthogonal polynomials
    m <- poly(1:6, degree = 3, simple = TRUE)
    m
    
    # the terms are uncorrelated. that's why they are "orthogonal".
    zapsmall(cor(m))
    
    # raw polynomials
    m <- poly(1:6, degree = 3, simple = TRUE, raw = TRUE)
    m
    
    # raw polynomials are highly correlated.
    round(cor(m), 2)
    
    ## ------------------------------------------------------------------------
    library(polypoly)
    xs <- 1:40
    poly_mat <- poly(xs, degree = 5)
    poly_melt(poly_mat)
    
    ## ----example, fig.width = 5, fig.height = 3------------------------------
    poly_plot(poly_mat)
    
    ## ----raw-example, fig.width = 5, fig.height = 3--------------------------
    poly_raw_mat  <- poly(-10:10, degree = 3, raw = TRUE)
    poly_plot(poly_raw_mat)
    
    ## ----raw-by-degree1,  fig.width = 5, fig.height = 3----------------------
    poly_plot(poly_raw_mat, by_observation = FALSE)
    
    ## ----sum, fig.width = 5, fig.height = 3----------------------------------
    library(ggplot2)
    poly_plot(poly_mat) + 
      stat_summary(aes(color = "sum"), fun.y = "sum", geom = "line", size = 1) + 
      theme_minimal()
    
    ## ------------------------------------------------------------------------
    poly_plot_data(poly_mat, by_observation = FALSE)
    
    ## ------------------------------------------------------------------------
    # For each column in a matrix, return difference between max and min values
    col_range <- function(matrix) {
      apply(matrix, 2, function(xs) max(xs) - min(xs))  
    }
    
    p1 <- poly(0:9, degree = 2)
    p2 <- poly(rep(0:9, 18), degree = 2)
    
    col_range(p1)
    col_range(p2)
    
    ## ----rescaled,  fig.width = 5, fig.height = 3----------------------------
    col_range(poly_rescale(p1, scale_width = 1))
    col_range(poly_rescale(p2, scale_width = 1))
    
    poly_plot(poly_rescale(p2, scale_width = 1), by_observation = FALSE)
    
    ## ------------------------------------------------------------------------
    df <- tibble::as_tibble(lme4::sleepstudy)
    print(df)
    
    poly_add_columns(df, Days, degree = 3)
    
    ## ------------------------------------------------------------------------
    poly_add_columns(df, Days, degree = 3, prefix = "poly_", scale_width = 1)
    
    ## ----sleepstudy, fig.width = 5, fig.height = 3---------------------------
    df <- poly_add_columns(df, Days, degree = 3, scale_width = 1)
    zapsmall(cor(df[c("Days1", "Days2", "Days3")]))
    
    ## ----splines,  fig.width = 5, fig.height = 3-----------------------------
    poly_plot(splines::bs(1:100, 10, intercept = TRUE))
    poly_plot(splines::ns(1:100, 10, intercept = FALSE))
    
    ## ----trees1, fig.width = 5, fig.height = 3-------------------------------
    library(lme4)
    df <- tibble::as_tibble(Orange)
    df$Tree <- as.character(df$Tree)
    df
    
    ggplot(df) + 
      aes(x = age, y = circumference, color = Tree) + 
      geom_line()
    
    ## ------------------------------------------------------------------------
    df <- poly_add_columns(Orange, age, 3, scale_width = 1)
    
    model <- lmer(
      scale(circumference) ~ age1 + age2 + age3 + (age1 + age2 + age3 | Tree), 
      data = df)
    summary(model)
    
    ## ------------------------------------------------------------------------
    poly_mat <- poly_rescale(poly(df$age, degree = 3), 1)
    
    # Keep only seven rows because there are 7 observations per tree
    poly_mat <- poly_mat[1:7, ]
    
    pred_mat <- cbind(constant = 1, poly_mat)
    pred_mat
    
    ## ------------------------------------------------------------------------
    weighted <- pred_mat %*% diag(fixef(model))
    colnames(weighted) <- colnames(pred_mat)
    
    ## ----trees-comparison, fig.width = 7, fig.height = 3---------------------
    df_raw <- poly_melt(pred_mat)
    df_raw$predictors <- "raw"
    
    df_weighted <- poly_melt(weighted)
    df_weighted$predictors <- "weighted"
    
    df_both <- rbind(df_raw, df_weighted)
    
    # Only need the first 7 observations because that is one tree
    ggplot(df_both[df_both$observation <= 7, ]) + 
      aes(x = observation, y = value, color = degree) + 
      geom_line() + 
      facet_grid(. ~ predictors) + 
      labs(color = "term")
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/polypoly-overview.OK')

```

### LINKED ISSUE #16: Nested hook execution in package "KraljicMatrix"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/KraljicMatrix-kraljic.R
Error in хxкуV : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: %>% ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In хxкуV :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/KraljicMatrix-kraljic.sqlite',verbose=FALSE)                                                                                                                                                                                                                                                                                                                                                                                         
dyntrace(dyntracer, {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- eval=FALSE---------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    #  psc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## # A tibble: 200 × 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    #  ##      PSC x_attribute y_attribute                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ##    <chr>       <int>       <int>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 1   D233        3.01        4.84                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 2   F352        4.34        5.64                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 3   T713        3.37        4.30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 4   K833        2.67        5.53                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 5   Q121        3.48        4.33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 6   C791        3.32        7.32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 7   Y207        3.48        5.42                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 8   W439        2.47        3.35                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 9   N290        1.66        4.02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## 10  C251        1.00        7.47                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    #  ## # ... with 190 more rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- echo=FALSE, warning=FALSE, message=FALSE---------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    psc <- tibble::tibble(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      PSC = c("D233", "F352", "T713", "K833", "Q121", "C791", "Y207", "W439", "N290", "C251", "U115", "Y679", "P256","B272", "Y895", "D663", "D400", "S883", "G274", "S229", "V324", "C529", "H379", "S528", "Q844", "X925", "A202", "W483", "Q507", "X898", "T845", "F318", "Y357", "Y536", "R954", "Y416", "E103", "I425", "C305", "W936", "H489", "N923", "G904", "I329", "T636", "G220", "W441", "C432", "N429", "N527", "X253", "N376", "L595", "K472", "H824", "X945", "D604", "E997", "K815", "E817", "D655", "R315", "P402", "F754", "Y853", "K960", "T856", "Z840", "H423", "Q618", "S855", "U622", "Q410", "G641", "Q255", "B187", "B238", "K980", "V809", "O854", "B455", "J637", "C309", "H426", "F973", "P184", "N763", "G691", "T373", "V761", "V437", "Y396", "S405", "I418", "R631", "I364", "D442", "D353", "J313", "Q795", "O131", "O920", "Y670", "V906", "O977", "J164", "M578", "V879", "M450", "E908", "B666", "D994", "N741", "A261", "H986", "W685", "Z776", "Z821", "A859", "S961", "E928", "F520", "X634", "B875", "C284", "X262", "V177", "C877", "D623", "M607", "P171", "E580", "I440", "D581", "E370", "M667", "G230", "G626", "G783", "N915", "X119", "Q697", "M496", "S868", "F334", "R777", "P941", "N436", "W932", "E537", "T317", "K942", "D715", "M176", "F452", "V162", "D983", "H278", "V649", "M775", "T269", "T173", "O522", "W299", "G852", "P291", "X597", "U310", "Q541", "M375", "A365", "L979", "X283", "T962", "E808", "A363", "I617", "B829", "G698", "B188", "U646", "O288", "T127", "C901", "I116", "V870", "S346", "J758", "S965", "E619", "I682", "M354", "H562", "K482", "L568", "Z491", "A668", "T203", "J332", "G362"),                   
      x_attribute = c(3.01, 4.34, 3.37, 2.67, 3.48, 3.32, 3.48, 2.47, 1.66, 1.00, 1.40, 2.99, 4.93, 1.62, 1.00, 3.42, 2.66, 1.31, 3.24, 1.45, 2.70, 1.61, 3.99, 2.40, 1.77, 3.92, 2.88, 2.75, 3.37, 2.53, 2.94, 4.68, 5.00, 4.01, 1.18, 1.00, 4.46, 3.54, 1.00, 1.43, 1.00, 2.57, 2.41, 1.90, 3.39, 3.43, 2.84, 4.65, 3.95, 3.01, 1.69, 2.11, 3.73, 3.84, 1.33, 4.18, 3.25, 5.00, 2.85, 4.31, 2.95, 2.52, 5.00, 2.49, 1.64, 3.96, 2.57, 4.74, 2.46, 3.13, 4.32, 1.41, 4.66, 3.05, 4.95, 1.71, 2.03, 3.18, 2.05, 1.89, 2.42, 4.66, 4.12, 5.00, 3.46, 3.56, 3.30, 2.01, 4.22, 3.86, 4.24, 2.15, 3.28, 4.21, 2.35, 2.36, 2.83, 2.60, 2.60, 1.16, 2.37, 4.48, 3.98, 1.00, 3.88, 1.22, 2.31, 3.82, 2.57, 4.75, 3.51, 4.58, 3.82, 3.83, 2.67, 3.95, 4.53, 3.70, 3.75, 3.47, 3.18, 4.21, 5.00, 4.00, 4.91, 2.70, 2.28, 1.00, 1.00, 2.95, 3.40, 4.06, 1.22, 1.61, 3.48, 3.53, 2.41, 3.42, 2.60, 3.87, 2.62, 5.00, 3.76, 1.64, 2.68, 1.78, 1.56, 2.67, 3.80, 2.98, 2.46, 4.81, 4.03, 3.22, 5.00, 2.74, 1.86, 4.43, 3.31, 2.28, 4.01, 3.99, 2.21, 2.25, 2.72, 3.31, 4.54, 3.67, 4.19, 2.23, 3.49, 3.80, 5.00, 2.28, 3.97, 3.42, 2.10, 1.88, 2.02, 3.89, 1.00, 5.00, 2.60, 3.80, 4.32, 5.00, 3.01, 4.17, 2.46, 5.00, 2.38, 2.37, 2.13, 2.41, 1.74, 1.00, 3.78, 1.00, 3.07, 2.29),                                                                                                                                                                                                                                                                                                                                                                                                                          
      y_attribute = c(4.84, 5.64, 4.30, 5.53, 4.33, 7.32, 5.42, 3.35, 4.02, 7.47, 6.58, 1.00, 3.04, 2.46, 4.91, 5.49, 4.72, 5.73, 8.98, 7.57, 3.30, 2.65, 4.76, 5.75, 5.76, 4.60, 2.44, 7.98, 8.82, 5.11, 3.44, 4.23, 6.55, 1.75, 4.80, 6.32, 7.71, 3.50, 5.49, 6.52, 5.06, 2.48, 4.45, 5.60, 6.58, 2.79, 6.58, 6.05, 7.60, 3.51, 4.75, 4.83, 4.12, 7.88, 4.45, 6.83, 1.34, 1.53, 4.04, 6.55, 6.64, 6.24, 5.82, 5.67, 4.97, 4.04, 5.21, 4.87, 5.52, 4.02, 4.89, 5.46, 5.54, 1.40, 6.41, 2.46, 5.53, 6.90, 6.47, 5.93, 4.66, 3.15, 2.66, 5.58, 3.91, 5.09, 6.18, 2.63, 6.93, 1.20, 4.67, 6.77, 5.19, 6.15, 2.38, 6.78, 5.91, 5.74, 4.51, 4.56, 6.65, 4.32, 3.76, 6.34, 6.74, 5.23, 1.00, 5.03, 4.39, 7.11, 6.11, 4.52, 3.93, 6.76, 4.34, 6.46, 5.05, 7.75, 1.54, 1.10, 7.36, 4.61, 5.19, 4.92, 2.07, 6.54, 5.81, 8.37, 6.50, 4.22, 3.00, 6.68, 4.99, 4.88, 5.27, 3.71, 1.36, 3.37, 6.80, 4.70, 5.27, 4.19, 7.50, 2.86, 1.18, 6.96, 4.40, 3.98, 3.58, 3.00, 3.06, 1.50, 4.17, 4.42, 4.36, 6.96, 5.51, 3.86, 7.40, 5.63, 4.08, 5.04, 7.29, 9.54, 2.72, 5.77, 6.23, 5.50, 4.32, 3.00, 3.30, 6.41, 4.52, 4.74, 6.46, 2.99, 6.77, 6.16, 6.28, 3.63, 10.00, 5.00, 8.18, 4.76, 7.30, 5.88, 8.21, 7.48, 6.02, 3.65, 7.21, 2.66, 5.15, 6.38, 5.95, 5.74, 4.30, 2.96, 5.89, 2.63)                                                                                                                                                                                                                                                                                                                                                                                                                          
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- eval=FALSE---------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    #  SAVF_preferred_rho(desired_x = c(3, 4, 5),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    #                     desired_v = c(.8, .9, 1),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    #                     x_low = 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    #                     x_high = 5,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    #                     rho_low = 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    #                     rho_high = 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    #  ## [1] 0.6531                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- echo=FALSE---------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    SAVF_score <- function(x, x_low, x_high, rho){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      # return error if x_low is not less than x_high                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      if(x_low >= x_high){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        stop("`x_low` must be less than `x_high`", call. = FALSE)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      # return error if rho is not a single value
      if (length(rho) != 1) {
        stop("`rho` must be a numeric value of length 1", call. = FALSE)
      }
    
      # generate SAVF values
      value <- (1 - exp(-rho * (x - x_low))) / (1 - exp(-rho * (x_high - x_low)))
    
      # return values
      return(value)
    
    }
    
    SAVF_plot <- function(desired_x, desired_v, x_low, x_high, rho){
    
      # return error if x_low is not less than x_high
      if(x_low >= x_high){
        stop("`x_low` must be less than `x_high`", call. = FALSE)
      }
    
      # return error if rho is not a single value
      if (length(rho) != 1) {
        stop("`rho` must be a numeric value of length 1", call. = FALSE)
      }
    
      # create string of x values
      x <- seq(x_low, x_high, by = (x_high - x_low) / 1000)
      v <- SAVF_score(x, x_low, x_high, rho)
    
      # create data frames to plot
      df <- data.frame(x = x, v = v)
      desired <- data.frame(x = desired_x, v = desired_v)
    
      ggplot2::ggplot(df, ggplot2::aes(x, v)) +
        ggplot2::geom_line() +
        ggplot2::geom_point(data = desired, ggplot2::aes(x, v), shape = 23, size = 2, fill = "white")
    
    }
    
    ## ---- fig.align='center', fig.height=3, fig.width=6----------------------
    
    
    SAVF_plot(desired_x = c(3, 4, 5),
              desired_v = c(.8, .9, 1),
              x_low = 1,
              x_high = 5,
              rho = 0.6531)
    
    ## ---- echo=FALSE---------------------------------------------------------
    SAVF_plot_rho_error <- function(desired_x, desired_v, x_low, x_high, rho_low, rho_high){
    
      # return error if x_low is not less than x_high
      if(x_low >= x_high){
        stop("`x_low` must be less than `x_high`", call. = FALSE)
      }
    
      # return error if rho_low is not less than rho_high
      if(rho_low >= rho_high){
        stop("`rho_low` must be less than `rho_high`", call. = FALSE)
      }
    
      # compute sequence of rho values
      rho <- seq(rho_low, rho_high, by = (rho_high - rho_low) / 10000)
      rho <- rho[rho != 0]
    
      # compute deltas between preferred and fitted values
      delta <- sapply(rho, function(x) sum((SAVF_score(desired_x, x_low, x_high, x) - desired_v)^2))
    
      # return rho that produces smallest error
      true_rho <- rho[which(delta == min(delta))]
    
      # plot value
      df <- data.frame(rho = rho, delta = delta)
      ggplot2::ggplot(df, ggplot2::aes(rho, delta)) +
        ggplot2::geom_line() +
        ggplot2::geom_point(ggplot2::aes(true_rho, min(delta)), shape = 23, size = 2, fill = "white")
    
    }
    
    ## ---- fig.align='center', fig.height=3, fig.width=6----------------------
    SAVF_plot_rho_error(desired_x = c(3, 4, 5),
                        desired_v = c(.75, .9, 1),
                        x_low = 1,
                        x_high = 5,
                        rho_low = 0,
                        rho_high = 1)
    
    ## ---- echo=FALSE---------------------------------------------------------
    SAVF_score <- function(x, x_low, x_high, rho){
    
      # return error if x_low is not less than x_high
      if(x_low >= x_high){
        stop("`x_low` must be less than `x_high`", call. = FALSE)
      }
    
      # return error if rho is not a single value
      if (length(rho) != 1) {
        stop("`rho` must be a numeric value of length 1", call. = FALSE)
      }
    
      # generate SAVF values
      value <- (1 - exp(-rho * (x - x_low))) / (1 - exp(-rho * (x_high - x_low)))
    
      # return values
      return(value)
    
    }
    
    ## ---- collapse=TRUE, message=FALSE, warning=FALSE------------------------
    # using dplyr to add a new variable while preserving existing data
    library(dplyr)
    
    # here we are assuming we found the appropriate rho value for the y attribute using
    # the same process as mentioned above
    psc <- psc %>%
      mutate(x_SAVF_score = SAVF_score(x_attribute, 1, 5, .653),
             y_SAVF_score = SAVF_score(y_attribute, 1, 10, .70))
    
    psc
    
    ## ---- echo=FALSE---------------------------------------------------------
    kraljic_matrix <- function(data, x, y){
    
      # return error if x or y are not numeric values
      x_col <- data[[deparse(substitute(x))]]
      y_col <- data[[deparse(substitute(y))]]
    
      if(!is.numeric(x_col) | !is.numeric(y_col)){
        stop("data for both column inputs must be numeric", call. = FALSE)
      }
    
      # plot Kraljic Matrix
      ggplot2::ggplot(data, ggplot2::aes_string(deparse(substitute(x)), deparse(substitute(y)))) +
        ggplot2::geom_point() +
        ggplot2::geom_vline(xintercept = .5) +
        ggplot2::geom_hline(yintercept = .5) +
        ggplot2::coord_cartesian(xlim = c(0,1), ylim = c(0,1)) +
        ggplot2::scale_x_reverse()
    }
    
    ## ---- fig.align='center', fig.width=7, fig.height=5----------------------
    kraljic_matrix(psc, x_SAVF_score, y_SAVF_score)
    
    ## ---- echo=FALSE---------------------------------------------------------
    kraljic_quadrant <- function(x, y){
    
      ifelse(x > .5 & y >= .5, "Leverage",
             ifelse(x > .5 & y < .5, "Critical",
                    ifelse(x <= .5 & y >= .5, "Strategic",
                           ifelse(x < .5 & y < .5, "Bottleneck", NA))))
    
    }
    
    ## ---- collapse=TRUE------------------------------------------------------
    psc %>%
      mutate(quadrant = kraljic_quadrant(x_SAVF_score, y_SAVF_score))
    
    ## ---- echo=FALSE---------------------------------------------------------
    MAVF_score <- function(x, y, x_wt, y_wt){
    
      # return error if x and y are different lengths
      if(length(x) != length(y)){
        stop("`x` and `y` must be the same length", call. = FALSE)
      }
    
      # return error if x or y weights are not a single value
      if (length(x_wt) != 1 | length(y_wt) != 1) {
        stop("x and y weights must be numeric values of length 1", call. = FALSE)
      }
    
      x * x_wt + y * y_wt + (1 - x_wt - y_wt) * x * y
    
    }
    
    ## ---- collapse=TRUE------------------------------------------------------
    psc %>%
      mutate(MAVF = MAVF_score(x_SAVF_score, y_SAVF_score, 0.65, 0.35))
    
    ## ---- collapse=TRUE------------------------------------------------------
    psc %>%
      mutate(MAVF = MAVF_score(x_SAVF_score, y_SAVF_score, 0.65, 0.35),
             quadrant = kraljic_quadrant(x_SAVF_score, y_SAVF_score)) %>%
      filter(quadrant == "Leverage") %>%
      top_n(10, wt = MAVF)
    
    ## ---- echo=FALSE---------------------------------------------------------
    MAVF_sensitivity <- function(data, x, y, x_wt_min, x_wt_max, y_wt_min, y_wt_max){
    
      # return error if x_wt_min is not less than x_wt_max
      if(x_wt_min >= x_wt_max){
        stop("`x_wt_min` must be less than `x_wt_max`", call. = FALSE)
      }
    
      # return error if y_wt_min is not less than y_wt_max
      if(y_wt_min >= y_wt_max){
        stop("`y_wt_min` must be less than `y_wt_max`", call. = FALSE)
      }
    
      # create random wts
      x_wt <- runif(1000, min = x_wt_min, max = x_wt_max)
      y_wt <- runif(1000, min = y_wt_min, max = y_wt_max)
      w_wt <- 1 - x_wt - y_wt
    
      # parse out vectors from data
      x_col <- data[[deparse(substitute(x))]]
      y_col <- data[[deparse(substitute(y))]]
    
      # create vectors to fill
      Min. <- vector(mode = "numeric", length = nrow(data))
      `1st Qu.` <- vector(mode = "numeric", length = nrow(data))
      Median <- vector(mode = "numeric", length = nrow(data))
      Mean <- vector(mode = "numeric", length = nrow(data))
      `3rd Qu.` <- vector(mode = "numeric", length = nrow(data))
      Max. <- vector(mode = "numeric", length = nrow(data))
      Range <- vector(mode = "numeric", length = nrow(data))
    
      # loop through to compute values for each x y pair
      for(i in 1:nrow(data)){
        s <- summary(x_col[i] * x_wt + y_col[i] * y_wt + (1 - x_wt - y_wt) * x_col[i] * y_col[i])
        Min.[i] <- s[1]
        `1st Qu.`[i] <- s[2]
        Median[i] <- s[3]
        Mean[i] <- s[4]
        `3rd Qu.`[i] <- s[5]
        Max.[i] <- s[6]
        Range[i] <- s[6] - s[1]
      }
    
      # add new columns
      data$MAVF_Min <- Min.
      data$MAVF_1st_Q <- `1st Qu.`
      data$MAVF_Median <- Median
      data$MAVF_Mean <- Mean
      data$MAVF_3rd_Q <- `3rd Qu.`
      data$MAVF_Max <- Max.
      data$MAVF_Range <- Range
    
    
      # return data
      data
    
    }
    
    ## ---- collapse=TRUE------------------------------------------------------
    MAVF_sensitivity(psc,
                     x = x_SAVF_score,
                     y = y_SAVF_score,
                     x_wt_min = .55,
                     x_wt_max = .75,
                     y_wt_min = .25,
                     y_wt_max = .45) %>%
      select(PSC, starts_with("MAVF"))
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/KraljicMatrix-kraljic.OK')

```

### LINKED ISSUE #17: Nested hook execution in package "heemod"
I got the following log:
```
[1/11] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/heemod-a_introduction.R
No named state -> generating names.
No named state -> generating names.
No named model -> generating names.
Scale for 'colour' is already present. Adding another scale for 'colour',
which will replace the existing scale.
Scale for 'colour' is already present. Adding another scale for 'colour',
which will replace the existing scale.
[1/11] Done executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/heemod-a_introduction.R
[2/11] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/heemod-k_calibration.R
Error in hùŽV : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: run_model ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: There were 11 warnings (use warnings() to see them)
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/heemod-a_introduction.sqlite',verbose=FALSE)                                                                                                                                                                                                                                                                                                                                                                                         
dyntrace(dyntracer, {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- echo=FALSE, include=FALSE------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    library(heemod)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    mat_trans <- define_transition(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
      .9, .1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      .2, .8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    mat_trans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    state_A <- define_state(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      cost = 1234,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      utility = 0.85                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    state_A                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    state_B <- define_state(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      cost = 4321,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      utility = 0.50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    state_B                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    strat <- define_strategy(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      transition = mat_trans,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      state_A,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
      state_B                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    strat                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    res_mod <- run_model(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      strat,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      cycles = 10,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      cost = cost,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      effect = utility                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    res_mod                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- fig.width = 6, fig.height=4, fig.align='center'--------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    plot(res_mod)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ## ---- fig.align='center', fig.height=4, fig.width=6, message=FALSE-------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    library(ggplot2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    plot(res_mod) +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
      xlab("Time") +
      ylab("N") +
      theme_minimal() +
      scale_color_brewer(
        name = "State",
        palette = "Set1"
      )
    
    ## ---- fig.align='center', fig.height=4, fig.width=6, message=FALSE-------
    library(ggplot2)
    
    plot(res_mod, bw = TRUE)
    
    ## ------------------------------------------------------------------------
    head(get_counts(res_mod))
    head(get_values(res_mod))
    
    ## ------------------------------------------------------------------------
    rate_to_prob(r = 162, per = 1000, to = 5)
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/heemod-a_introduction.OK')

```

### LINKED ISSUE #18: Nested hook execution in package "carpenter"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/carpenter-carpenter.R
Error in  萣"dU : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: build_table ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In 热b"dU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/carpenter-carpenter.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ---- echo = FALSE-------------------------------------------------------
    knitr::opts_chunk$set(
      comment = "#>"
    )
    
    ## ------------------------------------------------------------------------
    library(magrittr)
    library(carpenter)
    head(iris)
    outline_table(iris, 'Species') 
    
    ## ------------------------------------------------------------------------
    outline_table(iris, 'Species') %>% 
        add_rows('Sepal.Length', stat_meanSD) 
    
    ## ------------------------------------------------------------------------
    outline_table(iris, 'Species') %>% 
        add_rows(c('Sepal.Length', 'Petal.Length'), stat_meanSD) %>%
        add_rows('Sepal.Width', stat_medianIQR) 
    
    ## ------------------------------------------------------------------------
    tab <- outline_table(iris, 'Species') %>% 
        add_rows(c('Sepal.Length', 'Petal.Length'), stat_meanSD) %>%
        add_rows('Sepal.Width', stat_medianIQR)  %>% 
        renaming('header', c('Measures', 'Setosa', 'Versicolor', 'Virginica')) %>% 
        renaming('rows', function(x) gsub('\\.', ' ', x))
    tab
    
    ## ------------------------------------------------------------------------
    build_table(tab)
    
    ## ------------------------------------------------------------------------
    library(dplyr, quietly = TRUE)
    mtcars %>% 
        mutate(
            gear = as.factor(gear),
            vs = as.factor(vs)
        ) %>% 
        outline_table('vs') %>% 
        add_rows('mpg', stat_meanSD) %>%
        add_rows('drat', stat_medianIQR) %>% 
        add_rows('gear', stat_nPct) %>% 
        renaming('header', c('Measures', 'V-engine', 'Straight engine')) %>% 
        renaming('rows', function(x) x %>% 
                     gsub('drat', 'Read axle ratio', .) %>% 
                     gsub('mpg', 'Miles/gallon', .) %>% 
                     gsub('gear', 'Number of gears', .)) %>% 
        build_table()
    
    ## ------------------------------------------------------------------------
    iris %>% 
        outline_table() %>% 
        add_rows('Sepal.Length', stat_meanSD) %>%
        add_rows('Sepal.Width', stat_medianIQR) %>% 
        renaming('header', c('Measures', 'Values')) %>% 
        build_table() 
    
    ## ---- eval=FALSE---------------------------------------------------------
    #  iris %>%
    #      outline_table() %>%
    #      add_rows('Sepal.Length', stat_meanSD) %>%
    #      add_rows('Sepal.Width', stat_medianIQR) %>%
    #      renaming('header', c('Measures', 'Values')) %>%
    #      build_table(finish = FALSE) %>%
    #      write.csv('table1.csv', row.names = FALSE)
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/carpenter-carpenter.OK')

```

### LINKED ISSUE #19: Nested hook execution in package "covmat"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/covmat-CovarianceEstimation.R
Loading required package: mvtnorm
Loading required package: RMTstat
Loading required package: grid
Loading required package: zoo

Attaching package: âzooâ

The following objects are masked from âpackage:baseâ:

    as.Date, as.Date.numeric


Attaching package: âxtsâ

The following objects are masked from âpackage:dplyrâ:

    first, last

Loading required package: fit.models
Loading required package: foreach
Loading required package: PerformanceAnalytics

Attaching package: âPerformanceAnalyticsâ

The following object is masked from âpackage:graphicsâ:

    legend

Loading required package: rugarch
Loading required package: parallel
Error in È(4$}U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: library ... cpp_refMethods -> sapply -> lapply -> FUN -> <Anonymous> -> paste
In addition: Warning message:
In  ±È)}U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
Error in È(4$}U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: library ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Error in È(4$}U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: library ... namespaceImportFrom -> asNamespace -> loadNamespace
Error in È(4$}U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: library ... tryCatchList -> tryCatchOne -> doTryCatch -> loadNamespace
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_promise_created
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/covmat-CovarianceEstimation.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----setup, include=FALSE------------------------------------------------
    
    knitr::opts_chunk$set(fig.pos="h")
    knitr::opts_chunk$set(cache.path='./CovarianceEstimation_cache/')
    
    ## ----load_packages, results='hide', echo=FALSE, warning=FALSE, error=FALSE, message=FALSE----
    library(knitcitations)
    cleanbib()
    options("citation_format" = "pandoc")
    
    library(covmat)
    library(xts)
    library(robust)
    library(PortfolioAnalytics)
    library(rmgarch)
    
    ## ----load, eval=FALSE----------------------------------------------------
    #  library(devtools)
    #  install_github("arorar/covmat")
    
    ## ----doi, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE----------
    bib <- read.bibtex("references.bib")
    
    ## ----rmt-load------------------------------------------------------------
    
    data("dow30data")
    
    
    ## ---- eval=FALSE---------------------------------------------------------
    #  
    #  estRMT(R, Q =NA, cutoff = c("max", "each"),
    #         eigenTreat = c("average", "delete") ,
    #         numEig=1, parallel = TRUE)
    #  
    
    ## ----rmt-est, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE------
    model <- estRMT(dow30data, parallel=FALSE)
    
    
    ## ----rmt-plot, fig.width=8, fig.height=4, fig.keep='last'----------------
    
    plot(model)
    
    
    ## ----rmt-custommoment----------------------------------------------------
    
    custom.portfolio.moments <- function(R, portfolio) {
      momentargs <- list()
      momentargs$mu  <-  matrix(as.vector(apply(R,2, "mean")), ncol = 1)
      momentargs$sigma  <-  estRMT(R, parallel=FALSE)$cov
      momentargs$m3 <- matrix(0, nrow=ncol(R), ncol=ncol(R)^2)
      momentargs$m4 <- matrix(0, nrow=ncol(R), ncol=ncol(R)^3)
    
      return(momentargs)
    }
    
    ## ----rmt-portfoliospec---------------------------------------------------
    
    pspec.lo <- portfolio.spec(assets = colnames(dow30data))
    
    #long-only
    pspec.lo <- add.constraint(pspec.lo, type="full_investment")
    pspec.lo <- add.constraint(pspec.lo, type="long_only")
    
    pspec.lo <- add.objective(portfolio=pspec.lo, type="return", name="mean")
    pspec.lo <- add.objective(portfolio=pspec.lo, type="risk", name="var")
    
    
    ## ----rmt-run, warning=FALSE, error=FALSE, message=FALSE, eval = FALSE----
    #  
    #  opt.ordinary <-
    #    optimize.portfolio.rebalancing(dow30data, pspec.lo,
    #                                   optimize_method="quadprog",
    #                                   rebalance_on="months",
    #                                   training_period=120,
    #                                   trailing_periods=120)
    #  opt.rmt <-
    #    optimize.portfolio.rebalancing(dow30data, pspec.lo,
    #                                   optimize_method="quadprog",
    #                                   momentFUN = "custom.portfolio.moments",
    #                                   rebalance_on="months",
    #                                   training_period=120,
    #                                   trailing_periods=120)
    
    ## ----rmt-results, eval = FALSE-------------------------------------------
    #  
    #  ordinary.wts <- na.omit(extractWeights(opt.ordinary))
    #  ordinary <- Return.rebalancing(R=dow30data, weights=ordinary.wts)
    #  
    #  rmt.wts <- na.omit(extractWeights(opt.rmt))
    #  rmt <- Return.rebalancing(R=dow30data, weights=rmt.wts)
    #  
    #  rmt.strat.rets <- merge.zoo(ordinary,rmt)
    #  colnames(rmt.strat.rets) <- c("ordinary", "rmt")
    #  
    
    ## ----rmt-results-main,  results='hide', echo=FALSE, warning=FALSE, error=FALSE, message=FALSE----
    
    filepath <- "./CovarianceEstimation_cache/rmt_strategy_rets.RData"
    
    if (file.exists(filepath)) {
      load(filepath)
    } else {
      opt.ordinary <- 
      optimize.portfolio.rebalancing(dow30data, pspec.lo, 
                                     optimize_method="quadprog",
                                     rebalance_on="months", 
                                     training_period=120,
                                     trailing_periods=120)
      opt.rmt <- 
        optimize.portfolio.rebalancing(dow30data, pspec.lo, 
                                       optimize_method="quadprog",
                                       momentFUN = "custom.portfolio.moments",
                                       rebalance_on="months", 
                                       training_period=120, 
                                       trailing_periods=120)
      
      ordinary.wts <- na.omit(extractWeights(opt.ordinary))
      ordinary <- Return.rebalancing(R=dow30data, weights=ordinary.wts)
      
      rmt.wts <- na.omit(extractWeights(opt.rmt))
      rmt <- Return.rebalancing(R=dow30data, weights=rmt.wts)
      
      rmt.strat.rets <- merge.zoo(ordinary,rmt)
      colnames(rmt.strat.rets) <- c("ordinary", "rmt")
      
      save(rmt.strat.rets, file = filepath)
    }
                                  
    
    ## ----rmtstratplots-------------------------------------------------------
    charts.PerformanceSummary(rmt.strat.rets,wealth.index = T, 
                              colorset = c("red","blue"), 
                              main=paste(c("Comparison of Portflio ",
                                         "Performance using two ",
                                         "different covariance matrices"),
                                         collapse=""), cex.legend = 1.3, 
                              cex.axis = 1.3, legend.loc = "topleft")
    
    
    ## ----isdcc-load----------------------------------------------------------
    
    data("etfdata")
    
    
    ## ---- eval=FALSE---------------------------------------------------------
    #  
    #  isdccfit(R, numRegimes, transMatbounds = c(2,10),
    #           dccBounds = c(0,1), w = NA, ...)
    #  
    
    ## ----isdcc-est, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, eval=FALSE----
    #  model.isdcc <- isdccfit(etfdata, numRegimes=3, parallelType = 1, itermax = 100)
    #  
    
    ## ----isdcc-est-main, results='hide' ,echo=FALSE, warning=FALSE, error=FALSE, message=FALSE----
    
    filepath <- "./CovarianceEstimation_cache/isdcc_model.RData"
    if (file.exists(filepath)) {
      load(filepath)
    } else {
      model.isdcc <- isdccfit(etfdata, numRegimes=3, parallelType = 1, itermax = 100)
      save(model.isdcc, file = filepath)
    }
    
    
    ## ----isdcc-plot, fig.width=8, fig.height=4, fig.keep='last'--------------
    
    plot(model.isdcc)
    
    
    ## ----isdcc-custommoment--------------------------------------------------
    
    custom.portfolio.moments.isdcc <- function(R, portfolio) {
      
      momentargs <- list()
      momentargs$mu  <-  matrix(as.vector(apply(R,2, "mean")), ncol = 1)
      
      result <- isdccfit(R, numRegimes = 2, itermax=100)
      ldate <- as.character(tail(index(R),1))
      maxProbIndex <- which.max(result$filtProb[ldate,])
      momentargs$sigma  <-  result$cov[[ldate]][[maxProbIndex]]
      
      momentargs$m3 <- matrix(0, nrow=ncol(R), ncol=ncol(R)^2)
      momentargs$m4 <- matrix(0, nrow=ncol(R), ncol=ncol(R)^3)
      
      return(momentargs)
    }
    
    
    
    custom.portfolio.moments.dcc <- function(R, portfolio) {
      
      momentargs <- list()
      momentargs$mu  <-  matrix(as.vector(apply(R,2, "mean")), ncol = 1)
      
      garch11.spec <- ugarchspec(mean.model = list(armaOrder = c(0,0)), 
                                variance.model = list(garchOrder = c(1,1)
                                              , model = "sGARCH"), 
                                distribution.model = "norm")
      
      dcc.garch11.spec <- dccspec(uspec = multispec( replicate(ncol(R), 
                                                      garch11.spec) ), 
                                 dccOrder = c(1,1), distribution = "mvnorm")
      
      dcc.fit <- dccfit(dcc.garch11.spec, data = R)
      momentargs$sigma  <-  rcov(dcc.fit)[,,as.character(tail(index(R),1))]
      
      momentargs$m3 <- matrix(0, nrow=ncol(R), ncol=ncol(R)^2)
      momentargs$m4 <- matrix(0, nrow=ncol(R), ncol=ncol(R)^3)
      
      return(momentargs)
    }
    
    
    ## ----isdcc-portfoliospec-------------------------------------------------
    
    datap <- etfdata["2009-07/"]
    
    pspec.lo.isdcc <- portfolio.spec(assets = colnames(datap))
    
    #long-only
    pspec.lo.isdcc <- add.constraint(pspec.lo.isdcc, type="full_investment")
    pspec.lo.isdcc <- add.constraint(pspec.lo.isdcc, type="long_only")
    
    pspec.lo.isdcc <- add.objective(portfolio=pspec.lo.isdcc, 
                                    type="return", name="mean")
    pspec.lo.isdcc <- add.objective(portfolio=pspec.lo.isdcc, 
                                    type="risk", name="var")
    
    
    ## ----isdcc-run, warning=FALSE, error=FALSE , message=FALSE, results='hide', eval=FALSE----
    #  
    #  ordinary <-
    #    optimize.portfolio.rebalancing(datap, pspec.lo.isdcc,
    #                                   optimize_method="quadprog",
    #                                   rebalance_on="months",
    #                                   training_period=120,
    #                                   trailing_periods=120)
    #  
    #  opt.dcc <-
    #    optimize.portfolio.rebalancing(datap, pspec.lo.isdcc,
    #                                    optimize_method="quadprog",
    #                                    momentFUN =
    #                                     "custom.portfolio.moments.dcc",
    #                                    rebalance_on="months",
    #                                    training_period=120,
    #                                    trailing_periods=120)
    #  
    #  opt.isdcc <-
    #    optimize.portfolio.rebalancing(datap, pspec.lo.isdcc,
    #                                            optimize_method="quadprog",
    #                                            momentFUN =
    #                                     "custom.portfolio.moments.isdcc",
    #                                            rebalance_on="months",
    #                                            training_period=120,
    #                                            trailing_periods=120)
    
    ## ----isdcc-results,  eval=FALSE------------------------------------------
    #  
    #  ord.wts <- na.omit(extractWeights(ordinary))
    #  ord <- Return.rebalancing(R=datap, weights=ord.wts)
    #  
    #  dcc.wts <- na.omit(extractWeights(opt.dcc))
    #  dcc <- Return.rebalancing(R=datap, weights=dcc.wts)
    #  
    #  isdcc.wts <- na.omit(extractWeights(opt.isdcc))
    #  isdcc <- Return.rebalancing(R=datap, weights=isdcc.wts)
    #  
    #  isdcc.strat.rets <- merge.zoo(merge.zoo(ord, dcc), isdcc)
    #  colnames(isdcc.strat.rets) <- c("ordinary", "dcc", "isdcc")
    #  
    
    ## ----isdcc-results-main,  results='hide', echo=FALSE, warning=FALSE, error=FALSE, message=FALSE----
    
    filepath <- "./CovarianceEstimation_cache/isdcc_strategy_rets.RData"
    if (file.exists(filepath)) {
      load(filepath)
    } else {
      ordinary <- 
      optimize.portfolio.rebalancing(datap, pspec.lo.isdcc, 
                                     optimize_method="quadprog",
                                     rebalance_on="months", 
                                     training_period=120,
                                     trailing_periods=120)
    
      opt.dcc <- 
        optimize.portfolio.rebalancing(datap, pspec.lo.isdcc, 
                                        optimize_method="quadprog",
                                        momentFUN = 
                                         "custom.portfolio.moments.dcc",
                                        rebalance_on="months",
                                        training_period=120,
                                        trailing_periods=120)
    
      opt.isdcc <- 
        optimize.portfolio.rebalancing(datap, pspec.lo.isdcc, 
                                                optimize_method="quadprog",
                                                momentFUN = 
                                         "custom.portfolio.moments.isdcc",
                                                rebalance_on="months",
                                                training_period=120,
                                                trailing_periods=120)
    
      ord.wts <- na.omit(extractWeights(ordinary))
      ord <- Return.rebalancing(R=datap, weights=ord.wts)
      
      dcc.wts <- na.omit(extractWeights(opt.dcc))
      dcc <- Return.rebalancing(R=datap, weights=dcc.wts)
      
      isdcc.wts <- na.omit(extractWeights(opt.isdcc))
      isdcc <- Return.rebalancing(R=datap, weights=isdcc.wts)
      
      isdcc.strat.rets <- merge.zoo(merge.zoo(ord, dcc), isdcc)
      colnames(isdcc.strat.rets) <- c("ordinary", "dcc", "isdcc")
      
      save(isdcc.strat.rets, file = filepath)
    }
    
    
    ## ----isdccstratplots, fig.width=10, fig.height=8-------------------------
    charts.PerformanceSummary(isdcc.strat.rets,wealth.index = T,
                              colorset = c("red","blue","green"), 
                              main=paste(c("Comparison of Portflio ",
                                         "Performance using two ",
                                         "different covariance matrices"),
                                         collapse=""), cex.legend = 1.3, 
                              cex.axis = 1.3, legend.loc = "topright") 
    
    ## ----rmtdata-load--------------------------------------------------------
    
    data("rmtdata")
    
    
    ## ---- eval=FALSE---------------------------------------------------------
    #  
    #  estSpikedCovariance(R, gamma = NA,
    #                        numOfSpikes = NA,
    #                        method = c("KNTest", "median-fitting"),
    #                        norm = c("Frobenius", "Operator", "Nuclear"),
    #                        pivot = 1, statistical = NA,
    #                        fit = NA)
    #  
    
    ## ----spike-plot, eval=FALSE----------------------------------------------
    #  
    #    plotSpikedCovariance(rmtdata)
    #  
    
    ## ----spike-plot-main,  results='hide',  echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.show='hide'----
    
    filepath <- "./CovarianceEstimation_cache/Shrinkage.png"
    if (!file.exists(filepath)) {
      png(file = filepath, width = 12, height = 10, units = "in", res = 300)
      plotSpikedCovariance(rmtdata)
      dev.off()
    }
    
    
    ## ---- eval=FALSE---------------------------------------------------------
    #  
    #  robustMultExpSmoothing(R, smoothMat = NA, startup_period = 10,
    #                           training_period = 60 , seed = 9999, trials = 50,
    #                           method = "L-BFGS-B", lambda = 0.2)
    #  
    
    ## ----croux-est, eval=FALSE-----------------------------------------------
    #  
    #  data("dow30data")
    #  symbols <- c('AAPL', 'GE', 'MSFT' , 'NKE', 'V')
    #  
    #  R <- dow30data[,which(colnames(dow30data) %in% symbols)]
    #  smoothfit <- robustMultExpSmoothing(R)
    #  
    
    ## ----croux-est-main, results='hide', echo=FALSE, warning=FALSE, error=FALSE, message=FALSE----
    library(optimx)
    
    data("dow30data")
    symbols <- c('AAPL', 'GE', 'MSFT' , 'NKE', 'V')
    
    R <- dow30data[,which(colnames(dow30data) %in% symbols)]
    
    filepath <- "./CovarianceEstimation_cache/croux_smoothfit.RData"
    if (file.exists(filepath)) {
      load(filepath)
    } else {
      smoothfit <- robustMultExpSmoothing(R) 
      save(smoothfit, file = filepath)
    }
    
    
    ## ----croux-plots1, fig.width=10, fig.height=6----------------------------
    
    plotmissing(R)
    
    
    ## ----croux-plots2, fig.width=10, fig.height=6----------------------------
    
    plotmissing(smoothfit$cleanValues)
    
    
    ## ----croux-cov-plots, fig.width=10, fig.height=6-------------------------
    
    rob <- covRob(R)$cov
    compareCov(smoothfit$covMat, rob, labels = c("Robust Croux", "Robust"))
    
    
    
    ## ----references, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE----
    #write.bibtex(file="references.bib")
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/covmat-CovarianceEstimation.OK')

```

### LINKED ISSUE #20: Nested hook execution in package "DeLorean"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/DeLorean-DeLorean.R
Loading required package: Rcpp
Error in Èèl¬U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: estimate.hyper ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In ðôðŽU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_promise_created

```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/DeLorean-DeLorean.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----setup, echo=F-------------------------------------------------------
    knitr::opts_chunk$set(
        fig.width=12,
        fig.height=12/1.618,
        out.width='685px',
        dpi=144,
        message=FALSE)
    
    ## ----guoData-------------------------------------------------------------
    library(DeLorean)
    library(dplyr)
    data(GuoDeLorean)
    # Limit number of cores to 2 for CRAN
    options(DL.num.cores=min(default.num.cores(), 2))
    
    ## ------------------------------------------------------------------------
    dl <- de.lorean(guo.expr, guo.gene.meta, guo.cell.meta)
    
    ## ------------------------------------------------------------------------
    dl <- estimate.hyper(
        dl,
        sigma.tau=0.5,
        length.scale=1.5,
        model.name='exact-sizes')
    
    ## ------------------------------------------------------------------------
    num.at.each.stage <- 5
    epi.sampled.cells <- guo.cell.meta %>%
        filter(capture < "32C" |
               "EPI" == cell.type |
               "ICM" == cell.type) %>%
        group_by(capture) %>%
        do(sample_n(., num.at.each.stage))
    dl <- filter_cells(dl, cells=epi.sampled.cells$cell)
    
    ## ----aov-----------------------------------------------------------------
    dl <- aov.dl(dl)
    
    ## ------------------------------------------------------------------------
    head(dl$aov)
    
    ## ------------------------------------------------------------------------
    tail(dl$aov)
    
    ## ---- exec=FALSE---------------------------------------------------------
    dl <- filter_genes(dl, genes=head(dl$aov, 20)$gene)
    
    ## ------------------------------------------------------------------------
    dl <- examine.convergence(dl)
    plot(dl, type='Rhat')
    
    ## ----plot----------------------------------------------------------------
    plot(dl, type='pseudotime')
    
    ## ------------------------------------------------------------------------
    dl <- make.predictions(dl)
    plot(dl, type='profiles')
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/DeLorean-DeLorean.OK')


```

### LINKED ISSUE #21: Nested hook execution in package "alluvial"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/alluvial-alluvial.R
Error in ÈØfyV : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: %>% ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In ÈØfyV :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/alluvial-alluvial.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----setup, cache=FALSE, include=FALSE-----------------------------------
    library(alluvial)
    library(dplyr)
    
    knitr::opts_chunk$set(
      fig.width=7, 
      fig.height=4,
      cache=FALSE
    )
    
    ## ----data----------------------------------------------------------------
    tit <- as.data.frame(Titanic, stringsAsFactors = FALSE)
    head(tit)
    
    ## ----example-------------------------------------------------------------
    alluvial(tit[,1:4], freq=tit$Freq,
             col = ifelse(tit$Survived == "Yes", "orange", "grey"),
             border = ifelse(tit$Survived == "Yes", "orange", "grey"),
             hide = tit$Freq == 0,
             cex = 0.7
    )
    
    ## ----alluvial_defaults_2-------------------------------------------------
    # Survival status and Class
    tit %>% group_by(Class, Survived) %>%
      summarise(n = sum(Freq)) -> tit2d
    
    alluvial(tit2d[,1:2], freq=tit2d$n)
    
    ## ----alluvial_defaults_3-------------------------------------------------
    # Survival status, Sex, and Class
    tit %>% group_by(Sex, Class, Survived) %>%
      summarise(n = sum(Freq)) -> tit3d
    
    alluvial(tit3d[,1:3], freq=tit3d$n)
    
    ## ----colors--------------------------------------------------------------
    alluvial(
      tit3d[,1:3], 
      freq=tit3d$n,
      col = ifelse( tit3d$Sex == "Female", "pink", "lightskyblue"),
      border = "grey",
      alpha = 0.7,
      blocks=FALSE
    )
    
    ## ----alluvial_hide-------------------------------------------------------
    alluvial(tit2d[,1:2], freq=tit2d$n, hide=tit2d$n < 150)
    
    ## ------------------------------------------------------------------------
    tit2d %>% select(Class, Survived, n) %>%
      filter(n < 150)
    
    ## ----data_layer----------------------------------------------------------
    d <- data.frame(
      x = c(1, 2, 3),
      y = c(3 ,2, 1),
      freq=c(1,1,1)
    )
    d
    
    ## ----layer_ex1, fig.width=3, fig.height=3, fig.show="hold"---------------
    alluvial(d[,1:2], freq=d$freq, col=1:3, alpha=1)
    # Reversing the order
    alluvial(d[ 3:1, 1:2 ], freq=d$freq, col=3:1, alpha=1)
    
    ## ----layer_ex2-----------------------------------------------------------
    alluvial(d[,1:2], freq=d$freq, col=1:3, alpha=1, 
             layer=3:1)
    
    ## ----layer_ex3-----------------------------------------------------------
    alluvial(tit3d[,1:3], freq=tit3d$n, 
             col = ifelse( tit3d$Survived == "Yes", "orange", "grey" ),
             alpha = 0.8,
             layer = tit3d$Survived == "No"
    )
    
    ## ----ordering_data-------------------------------------------------------
    tit %>% group_by(Sex, Age, Survived) %>%
      summarise( n= sum(Freq)) -> x
    
    tit %>% group_by(Survived, Age, Sex) %>%
      summarise( n= sum(Freq)) -> y
    
    ## ----ordering_x----------------------------------------------------------
    alluvial(x[,1:3], freq=x$n, 
             col = ifelse(x$Sex == "Male", "orange", "grey"),
             alpha = 0.8,
             blocks=FALSE
    )
    
    ## ----ordering_y----------------------------------------------------------
    alluvial(y[,1:3], freq=y$n, 
             # col = RColorBrewer::brewer.pal(8, "Set1"),
             col = ifelse(y$Sex == "Male", "orange", "grey"),
             alpha = 0.8,
             blocks = FALSE,
             ordering = list(
               order(y$Survived, y$Sex == "Male"),
               order(y$Age, y$Sex == "Male"),
               NULL
             )
    )
    
    ## ------------------------------------------------------------------------
    pal <- c("red4", "lightskyblue4", "red", "lightskyblue")
    
    tit %>%
      mutate(
        ss = paste(Survived, Sex),
        k = pal[ match(ss, sort(unique(ss))) ]
      ) -> tit
    
    
    alluvial(tit[,c(4,2,3)], freq=tit$Freq,
             hide = tit$Freq < 10,
             col = tit$k,
             border = tit$k,
             blocks=FALSE,
             ordering = list(
               NULL,
               NULL,
               order(tit$Age, tit$Sex )
    
             )
    )
    
    ## ---- eval=FALSE, echo=FALSE---------------------------------------------
    #  d <- expand.grid(a=1:2, b=1:2, c=1:2)
    #  d %>%
    #    mutate(
    #      z=a,
    #      n = rep(1, nrow(d))
    #    ) -> d
    #  
    #  alluvial(
    #    d[,1:4],
    #    freq=d$n,
    #    col=RColorBrewer::brewer.pal(8, "Paired"),
    #    blocks=FALSE,
    #    ordering = list(
    #      NULL,
    #      NULL,
    #      order(d$b),
    #      NULL
    #    )
    #    )
    
    ## ----session_info--------------------------------------------------------
    sessionInfo()
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/alluvial-alluvial.OK')

```

### LINKED ISSUE #22: Nested hook execution in package "cleanEHR"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/cleanEHR-tour.R
       site_id episode_id nhs_number pas_number         t_admission t_discharge
1: pseudo_site          1         NA         NA 1970-01-01 01:00:00        <NA>
2: pseudo_site          2         NA         NA 1970-01-01 01:00:00        <NA>
3: pseudo_site          3         NA         NA 1970-01-01 01:00:00        <NA>
4: pseudo_site          4         NA         NA 1970-01-01 01:00:00        <NA>
5: pseudo_site          5         NA         NA 1970-01-01 01:00:00        <NA>
6: pseudo_site          6         NA         NA 1970-01-01 01:00:00        <NA>
   parse_file parse_time pid index
1:         NA       <NA>   1     1
2:         NA       <NA>   2     2
3:         NA       <NA>   3     3
4:         NA       <NA>   4     4
5:         NA       <NA>   5     5
6:         NA       <NA>   6     6
Error in  : 
  DYNTRACE: encountered ACTIVE BINDING frame, missing implementation, confused
Calls: create.cctable -> <Anonymous>
In addition: Warning messages:
1: In Èx³2ÃU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
2: Removed 4 rows containing missing values (geom_vline). 
3: In Èx³2ÃU : NAs introduced by coercion
4: In X	OCÃU : NAs introduced by coercion
5: In Èx³2ÃU : NAs introduced by coercion
6: In Èx³2ÃU : NAs introduced by coercion
7: In Èx³2ÃU : NAs introduced by coercion
8: In Èx³2ÃU :
  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed.
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_promise_created
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_environment_lookup_var
Fatal error: error during cleanup
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/cleanEHR-tour.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ------------------------------------------------------------------------
    library(cleanEHR)
    data.path <- paste0(find.package("cleanEHR"), "/doc/sample_ccd.RData")
    load(data.path)
    
    ## ------------------------------------------------------------------------
    print(head(ccd@infotb))
    
    ## ------------------------------------------------------------------------
    # quickly check how many episodes are there in the dataset.
    ccd@nepisodes
    
    ## ---- fig.width=10, fig.height=11, out.width='700px', results='hide', message=FALSE, warning=FALSE----
    # check the heart rate, bilirubin, fluid balance, and drugs of episode_id = 7. 
    # NOTE: due to anonymisation reason, some episodes data cannot be displayed
    # properly. 
    episode.graph(ccd, 7, c("h_rate",  "bilirubin", "fluid_balance_d"))
    
    ## ---- fig.width=10, fig.height=6, out.width='700px', results='hide', message=FALSE, warning=FALSE----
    # contains all the 1D fields i.e. non-longitudinal
    tb1 <- sql.demographic.table(ccd)
    
    # filter out all dead patient. (All patients are dead in the dataset.)
    tb1 <- tb1[DIS=="D"]
    
    # subset variables we want (ARSD = Advanced respiratory support days,
    # apache_prob = APACHE II probability)
    tb <- tb1[, c("SEX", "ARSD", "apache_prob"), with=F]
    tb <- tb[!is.na(apache_prob)]
    
    # plot
    library(ggplot2)
    ggplot(tb, aes(x=apache_prob, y=ARSD, color=SEX)) + geom_point()
    
    
    ## ------------------------------------------------------------------------
    # To prepare a YAML configuration file like this. You write the following text
    # in a YAML file. 
    conf <- "
    NIHR_HIC_ICU_0108:
      shortName: hrate
    NIHR_HIC_ICU_0112:
      shortName: bp_sys_a
      dataItem: Systolic Arterial blood pressure - Art BPSystolic Arterial blood pressure
    NIHR_HIC_ICU_0093:
       shortName: sex
    "
    library(yaml)
    tb <- create.cctable(ccd, yaml.load(conf), freq=1)
    
    # a lazy way to do that. 
    tb <- create.cctable(ccd, list(NIHR_HIC_ICU_0108=list(), 
                             NIHR_HIC_ICU_0112=list(), 
                             NIHR_HIC_ICU_0093=list()), 
                         freq=1)
    print(tb$tclean)
    
    ## ------------------------------------------------------------------------
    tb$tclean[, mean(NIHR_HIC_ICU_0108, na.rm=T), by=c("site", "episode_id")]
    
    ## ---- fig.width=12, fig.height=12, out.width='700px', results='hide', message=FALSE, warning=FALSE----
    conf <-"
    NIHR_HIC_ICU_0108:
      shortName: hrate
      dataItem: Heart rate
      distribution: normal
      decimal_places: 0
      range:
        labels:
          red: (0, 300)
          amber: (11, 150)
        apply: drop_entry
      missingness: # remove episode if missingness is higher than 70% in any 24 hours interval 
        labels:
          yellow: 24
        accept_2d:
          yellow: 70 
        apply: drop_episode
    "
    
    ctb <- create.cctable(ccd, yaml.load(conf), freq=1)
    ctb$filter.ranges("amber") # apply range filters
    ctb$filter.missingness()
    ctb$apply.filters()
    
    cptb <- rbind(cbind(ctb$torigin, data="origin"), 
                  cbind(ctb$tclean, data="clean"))
    
    
    ggplot(cptb, aes(x=time, y=NIHR_HIC_ICU_0108, color=data)) + 
      geom_point(size=1.5) + facet_wrap(~episode_id, scales="free_x")
    
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/cleanEHR-tour.OK')

```

### LINKED ISSUE #23: Nested hook execution in package "janitor"
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/janitor-introduction.R
Error in Èžb9V : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: %>% ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In H¬e9V :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/janitor-introduction.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ---- echo = FALSE, message = FALSE--------------------------------------
    knitr::opts_chunk$set(collapse = T, comment = "#>")
    library(janitor)
    
    ## ---- message = FALSE, warning = FALSE-----------------------------------
    # Load dplyr for the %>% pipe
    library(dplyr)
    # Create a data.frame with dirty names
    test_df <- as.data.frame(matrix(ncol = 6))
    names(test_df) <- c("hIgHlo", "REPEAT VALUE", "REPEAT VALUE",
                        "% successful (2009)",  "abc@!*", "")
    
    ## ------------------------------------------------------------------------
    test_df %>%
      clean_names()
    
    ## ------------------------------------------------------------------------
    make.names(names(test_df))
    
    ## ------------------------------------------------------------------------
    x <- c("a", "b", "c", "c", NA)
    tabyl(x, sort = TRUE)
    
    ## ------------------------------------------------------------------------
    table(x)
    
    ## ------------------------------------------------------------------------
    mtcars %>%
      filter(gear > 3) %>%
      tabyl(cyl)
    
    ## ------------------------------------------------------------------------
    y <- c(1, 1, 2, 1, 2)
    x <- c("a", "a", "b", "b", NA)
    
    crosstab(x, y)
    crosstab(x, y, percent = "row")
    
    ## ------------------------------------------------------------------------
    dat <- data.frame(x, y)
    dat %>%
      crosstab(x, y, percent = "row")
    
    ## ---- message=FALSE, results = "hide"------------------------------------
    library(dplyr) ; library(tidyr)
    dat %>%
      group_by(x, y) %>%
      tally() %>%
      mutate(percent = n / sum(n, na.rm = TRUE)) %>%
      select(-n) %>%
      spread(y, percent, fill = 0) %>%
      ungroup()
    
    ## ------------------------------------------------------------------------
    mtcars %>%
      crosstab(cyl, gear) %>%
      adorn_crosstab()
    
    ## ------------------------------------------------------------------------
    get_dupes(mtcars, wt, cyl) # or mtcars %>% get_dupes(wt, cyl) if you prefer to pipe
    
    ## ------------------------------------------------------------------------
    excel_numeric_to_date(41103)
    excel_numeric_to_date(41103, date_system = "mac pre-2011")
    
    ## ------------------------------------------------------------------------
    q <- data.frame(v1 = c(1, NA, 3),
                    v2 = c(NA, NA, NA),
                    v3 = c("a", NA, "b"))
    q %>%
      remove_empty_cols() %>%
      remove_empty_rows()
    
    ## ------------------------------------------------------------------------
    mtcars %>%
      crosstab(am, cyl) %>%
      adorn_totals("row")
    
    ## ------------------------------------------------------------------------
    mtcars %>%
      crosstab(cyl, am) %>%
      ns_to_percents("col")
    
    ## ------------------------------------------------------------------------
    f <- factor(c("strongly agree", "agree", "neutral", "neutral", "disagree", "strongly agree"),
                levels = c("strongly agree", "agree", "neutral", "disagree", "strongly disagree"))
    top_levels(f)
    top_levels(f, n = 1, sort = TRUE)
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/janitor-introduction.OK')


```

### LINKED ISSUE #24: Nested hook execution in package "ForecastFramework"
I got the following log:
```
[2/4] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/ForecastFramework-DataPolymorphism.R
Loading required package: R6
Loading required package: lattice
Error in ÈH3U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning messages:
1: In ÈH3U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
2: In ÈH3U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
3: In  :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
4: In ÈH3U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted

```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/ForecastFramework-DataPolymorphism.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----setup, include=FALSE------------------------------------------------
    knitr::opts_chunk$set(echo = TRUE)
    library(dplyr)
    library(ForecastFramework)
    library(DAAG)
    
    ## ------------------------------------------------------------------------
    data("Orange")
    listFormData = ObservationList$new(
      data=Orange
    )
    
    ## ------------------------------------------------------------------------
    library(DAAG)
    data("bomregions")
    matrix_data = t(bomregions[1:8,c(10:17)])
    matrixFormData = IncidenceMatrix$new(
      data=matrix_data,
      colData = list(
        yr=bomregions[1:8,1]
      )
    )
    
    ## ----Comparison, warning = FALSE,message = FALSE-------------------------
    listFormData$formArray(
      row='Tree',
      col='age',
      val='circumference'
    )
    listFormData$mat
    matrixFormData$mat
    
    ## ------------------------------------------------------------------------
    model = MoveAheadModel$new()
    model$fit(listFormData)
    model$fit(matrixFormData)
    model$predict(matrixFormData)$mean()$mat
    model$predict(listFormData)$mean()$mat
    
    ## ----Class Changing------------------------------------------------------
    anotherMatrixFormData = IncidenceMatrix$new(listFormData)
    anotherMatrixFormData$mat
    listFormData$mat
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/ForecastFramework-DataPolymorphism.OK')


```

### PR DESCRIPTION
**Pull request by kondziu**
Lookup covers active binding and has proper error reporting. There are also some minor nit-picks for some of the code.

Summary of runnign selected packages:
fixes #24 ForecastFramework NO ERRORS
fixes #23 janitor NO ERRORS
fixes #22 cleanEHR UNRELATED ERROR (unbalanced stack, unknown)
fixes #21 alluvial NO ERRORS
fixes #20 DeLorean UNRELATED ERROR (object 'fit' not found)
fixes #19 covmat UNRELATED ERROR (file ont found)
fixes #18 carpenter NO ERRORS
fixes #17 heemod UNRELATED ERROR (unbalanced stack, unknown)
fixes #16 KraljicMatrix NO ERRORS
fixes #15 polypoly NO ERRORS
fixes #14 nonmemica UNRELATED ERROR (missing package)
fixes #13 queuecomputer NO ERRORS
fixes #12 tidytext UNRELATED ERROR (unkonwn package)
fixes #11 shazam UNRELATED ERROR (cannot infer type of opcode : 7)

### CODE REVIEW

File: src/lookup.cpp [hunk 1]
```diff
@@ -65,33 +62,50 @@ SEXP find_promise_in_single_environment(const SEXP symbol, const SEXP rho) {
...
 #ifdef USE_GLOBAL_CACHE
     if (rho == R_GlobalEnv)
         return find_promise_in_global_cache(symbol);
     else
 #endif
-        return R_UnboundValue;
+        return {lookup_status::SUCCESS, R_UnboundValue};
 }
+
+string lookup_status_to_string(lookup_status status) {
```
Comment (aviralg) [inline src/lookup.cpp]: Maybe we can rename this to `to_string` because C++ allows overloading functions on argument type.

File: src/sexptypes.cpp [hunk 2]
```diff
@@ -82,101 +82,53 @@ void get_full_type_inner(SEXP sexp, SEXP rho, full_sexp_type &result,
...
 
-        get_full_type_inner(symbol_points_to, rho, result, visited);
+                get_full_type_inner(symbol_points_to, rho, result, visited);
 
-        return;
+                return;
+            }
+
+            case lookup_status::SUCCESS_ACTIVE_BINDING: {
+                result.push_back(sexp_type::ACTIVE_BINDING);
```
Comment (aviralg) [inline src/sexptypes.cpp]: Do we really need this? This seems like an internal detail, not a value type.

File: src/lookup.h [hunk 3]
```diff
@@ -5,6 +5,22 @@
...
+    SUCCESS_ACTIVE_BINDING,
+    FAIL_USER_DEFINED_DATABASE,
+    FAIL_ENVIRONMENT_IS_NIL,
+    FAIL_ARGUMENT_IS_NOT_AN_ENVIRONMENT,
+    FAIL_GLOBAL_CACHE
+};
+
+std::string lookup_status_to_string(lookup_status);
+
+struct lookup_result {
```
Comment (aviralg) [inline src/lookup.h]: Why do you prefer returning a `struct` instead of logging `FAIL_` conditions at their place of occurrence and returning the looked up value in case of `SUCCESS_` ? Eventually, these enum values are used to log warnings anyways, isn't it so?

File: src/sexptypes.cpp (hunk 2 above)
Comment (kondziu) [reply src/sexptypes.cpp]: I put it in because there's a skip from the symbol to the expression inside the function. So, if you define the active binding as `makeActiveBinding("f", function() 2+2, some.env)` I will see `f` as SYMSXP, and then `2+2` as LANGSXP. The `function() ...` part is lost and I wanted to make that explicit. (I also can't assume it's a closure, because it can be any function).

File: src/lookup.cpp (hunk 1 above)
Comment (kondziu) [reply src/lookup.cpp]: Maybe. What's the benefit?

File: src/lookup.h (hunk 3 above)
Comment (kondziu) [reply src/lookup.h]: This happens because the function is used in various contexts, and I wanted to make it general enough so that it can be re-used without modifications if possible. Returning a struct allows me to act differently when there's an active binding, and possibly, in the future, we can handle the errors better, or mitigate them. It's the sort of mechanism you see with, say, file I/O in C: functions return a value and set an error value somewhere, with the exception that here I don't set a global variable, but stuff it all in a struct.

File: src/lookup.cpp (hunk 1 above)
Comment (kondziu) [reply src/lookup.cpp]: (This is a genuine question, I'm not trying to be difficult.)

**Comment by kondziu** [comment]
Sorry for unilaterally merging, but there don't seem to be any technical issues and so I want to start working with the new type data. We can come back to the software engineering aspects later on.
