### PR TITLE
Fix error handling and logging in the serializer

### LINKED ISSUE #3: Improve error handling
We need a mechanism for raising errors from within the tracer. The error should print on the console and exit the tracing. It should ideally not exit the R session. This is complicated by the fact that there is a probe that fires when errors are raised through R. So, when the tracer raises an error (from within a probe), it causes the `error` probe to fire as well leading to nested probe execution. This is again caught by the framework which tries to signal this error, repeating the same cycle again. This permanently leaves the interpreter in an unusable state requiring the user to manually kill the process.

### PR DESCRIPTION
**Pull request by aviralg**
This commit replaces all warning and error reporting calls
with their `dyntrace` equivalents.

Error handling has been significantly improved, many new
cases have been handled.

Resolves #3

### CODE REVIEW

File: src/SqlSerializer.h [hunk 1]
```diff
@@ -74,25 +75,26 @@ class SqlSerializer {
...
-    sqlite3_stmt *insert_promise_evaluation_statement = nullptr;
-    sqlite3_stmt *insert_promise_return_statement = nullptr;
-    sqlite3_stmt *insert_promise_lifecycle_statement = nullptr;
-    sqlite3_stmt *insert_promise_argument_type_statement = nullptr;
-    sqlite3_stmt *insert_gc_trigger_statement = nullptr;
-    sqlite3_stmt *insert_type_distribution_statement = nullptr;
-    sqlite3_stmt *insert_environment_statement = nullptr;
-    sqlite3_stmt *insert_variable_statement = nullptr;
-    sqlite3_stmt *insert_variable_action_statement = nullptr;
+    sqlite3_stmt *insert_metadata_statement = NULL;
```
Comment (kondziu) [inline src/SqlSerializer.h]: I got this form Peta, who said that using nullptr is preferable to NULL since nullptr is type checked. Not sure why you changed it.
