### PR TITLE
Fix unwinding partially and track environment

### LINKED ISSUE #38: Symbols' contents looked up in seeming the wrong environment
Symbols' contents are determined by looking them up in some environment. They are looked up in one environment first, if they are not found there, then, they are looked up in the environment above, etc. Symbols don't carry environment information like promises do (AFAIK).

In function `get_full_type_inner` when we see a symbol, we look it up in the environment we have at hand: the one that came with the promise.

**What happens**:

A symbol is looked up, returns a promise. The promise contents get looked up, it yields another symbol that is the same as the first symbol. The symbol gets looked up, but it returns the same promise as before. There is a cycle. See below promise events with `prom_id=256`

Small example:
```r
f <- function() { x=1; g(x) }
g <- function(x) { h(x) }
h <- function(x) { x + 1}
f()
```

```
> dyntrace(dt, f())
├─ begin
│  ├─ >> force promise prom_id=254 prom_type=LANG return_type=... full_type=LANG from_call_id=0 in_call_id=0 in_prom_id=0 parent_on_stack={type=none} depth=0 actual_distance_from_origin=0 effective_distance_from_origin=0
│  │  ├─ closure name=f fn_id=JEr+juXwO8OQhpezwuZVKg== call_id=473 args=[] parent={type=promise id=254} parent_call_id=0 parent_prom_id=254 definition_location= callsite_location= compiled=1 definition=function () {x = 1g(x)}
│  │  │  ├─ create promise_basic prom_id=255 prom_type=BCODE full_type=BCODE->SYM->REAL in_prom_id=254 parent_on_stack={type=call id473} depth=1
│  │  │  ├─ closure name=g fn_id=meaLMPrYsnilLkMkHX5zEA== call_id=474 args=[{name=x arg_id=597 prom_id=255}] parent={type=call id473} parent_call_id=473 parent_prom_id=254 definition_location= callsite_location= compiled=1 definition=function (x) {h(x)}
│  │  │  │  ├─ prom_arg_type prom_id=255 default_argument=0
│  │  │  │  ├─ create promise_basic prom_id=256 prom_type=BCODE full_type=BCODE->SYM->PROM->BCODE->SYM->... in_prom_id=254 parent_on_stack={type=call id474} depth=1
│  │  │  │  ├─ closure name=h fn_id=jYS8ZTxdgMdYVfUoxrqPWw== call_id=475 args=[{name=x arg_id=598 prom_id=256}] parent={type=call id474} parent_call_id=474 parent_prom_id=254 definition_location= callsite_location= compiled=1 definition=function (x) {x + 1}
│  │  │  │  │  ├─ prom_arg_type prom_id=256 default_argument=0
│  │  │  │  │  ├─ >> force promise prom_id=256 prom_type=BCODE return_type=... full_type=BCODE->SYM->PROM->BCODE->SYM->... from_call_id=475 in_call_id=475 in_prom_id=254 parent_on_stack={type=call id475} depth=1 actual_distance_from_origin=0 effective_distance_from_origin=0
│  │  │  │  │  │  ├─ >> force promise prom_id=255 prom_type=BCODE return_type=... full_type=BCODE->SYM->REAL from_call_id=474 in_call_id=475 in_prom_id=256 parent_on_stack={type=promise id=256} depth=2 actual_distance_from_origin=1 effective_distance_from_origin=1
│  │  │  │  │  │  │  ┴<< force promise prom_id=255 prom_type=BCODE return_type=REAL full_type=BCODE->SYM from_call_id=474 in_call_id=475 in_prom_id=256 parent_on_stack={type=promise id=256} depth=2 actual_distance_from_origin=1 effective_distance_from_origin=1
│  │  │  │  │  │  ┴<< force promise prom_id=256 prom_type=BCODE return_type=REAL full_type=BCODE->SYM from_call_id=475 in_call_id=475 in_prom_id=254 parent_on_stack={type=call id475} depth=1 actual_distance_from_origin=0 effective_distance_from_origin=0
│  │  │  │  │  ┴
│  │  │  │  ┴
│  │  │  ┴
│  │  ┴<< force promise prom_id=254 prom_type=LANG return_type=REAL full_type=LANG from_call_id=0 in_call_id=0 in_prom_id=0 parent_on_stack={type=none} depth=0 actual_distance_from_origin=0 effective_distance_from_origin=0
├─ end
[1] 2

```

### PR DESCRIPTION
**Pull request by kondziu**
It fixes some of the problems with unwinding the stack, but not completely: some packages still cause problems. This is #37.

It also fixes #38: type traces to remove the promises that have cycles.

### CODE REVIEW

File: src/lookup.cpp [hunk 1]
```diff
@@ -59,20 +59,20 @@ lookup_result find_binding_in_single_environment(const SEXP symbol, const SEXP r
             (!HASHASH(print_name))
                 ? (newhashpjw(CHAR(print_name)) % LENGTH(HASHTAB(rho)))
                 : (HASHVALUE(print_name) % LENGTH(HASHTAB(rho)));
-        return get_hash(hashcode, symbol, HASHTAB(rho));
+        return get_hash(hashcode, symbol, HASHTAB(rho), rho);
```
Comment (aviralg) [inline src/lookup.cpp]: We can just pass `rho` and have `get_hash` do `HASHTAB(rho)` inside its body.

File: src/sexptypes.cpp [hunk 2]
```diff
@@ -129,10 +124,14 @@ void get_full_type_inner(SEXP sexp, SEXP rho, full_sexp_type &result,
                 return;
```
Comment (aviralg) [inline src/sexptypes.cpp]: Can we end at active bindings? We know that an active binding means the symbol is bound to a function that will be called automatically when the symbol is looked up or reassigned. So, adding the type of function after active binding may not be insightful. Also, ending at active binding lets our script show the type of this symbol as ACTIVE_BINDING which is a useful thing to know in itself.

**Comment by aviralg** [comment]
This does not build. You seem to have accidentally pasted stuff from clipboard. Check line 62 in the panel on the right side of the following link -

https://github.com/PRL-PRG/promisedyntracer/commit/ab67a328b7c18720bccf3d83b6c84b4cc4131cb3#diff-806093116e1e073373bf6c2a424707b8
